services:
  bot:
    image: ghcr.io/Ne0shka/paradise-helper-app:latest
    container_name: bot
    restart: always
    environment:
      PYTHONUNBUFFERED: "1"
      API_ID: ""
      API_HASH: ""
      BOT_TOKEN: ""
    volumes:
      - type: bind
        source: ./bot.session
        target: /app/app/bot.session
